#!/usr/bin/bash

curl -s -X GET "http://192.168.56.101/?page=b7e44c7a40c5f80139f0a50f3650fb2bd8d00b0d24667c4c2ca32c88e13b758f" -H 'Referer: https://www.nsa.gov/' -H "User-Agent: ft_bornToSec" | grep -oP 'The flag is : \K[0-9a-f]{64}'